// BREEDS
export const GET_BREEDS_ATTEMPT = "GET_BREEDS_ATTEMPT";
export const GET_BREEDS_SUCCESS = "GET_BREEDS_SUCCESS";
export const GET_BREEDS_FAILURE = "GET_BREEDS_FAILURE";

export const GET_BREEDS_IMAGES_ATTEMPT = "GET_BREEDS_IMAGES_ATTEMPT";
export const GET_BREEDS_IMAGES_SUCCESS = "GET_BREEDS_IMAGES_SUCCESS";
export const GET_BREEDS_IMAGES_FAILURE = "GET_BREEDS_IMAGES_FAILURE";

// DOGS
export const GET_DOGS_ATTEMPT = "GET_DOGS_ATTEMPT";
export const GET_DOGS_SUCCESS = "GET_DOGS_SUCCESS";
export const GET_DOGS_FAILURE = "GET_DOGS_FAILURE";

// TEAM
export const ADD_TO_TEAM = "ADD_TO_TEAM";
export const REMOVE_FROM_TEAM = "REMOVE_FROM_TEAM";
